/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ArticleItem: typeof import('./src/components/ArticleItem.vue')['default']
    BackHeader: typeof import('./src/components/BackHeader.vue')['default']
    HomeContent1: typeof import('./src/components/HomeContent/HomeContent1.vue')['default']
    HomeContent2: typeof import('./src/components/HomeContent/HomeContent2.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    NoticeItem: typeof import('./src/components/NoticeItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShowUser: typeof import('./src/components/ShowUser.vue')['default']
    TheHeader: typeof import('./src/components/TheHeader.vue')['default']
    TheLogin: typeof import('./src/components/TheLogin.vue')['default']
    TheTabbar: typeof import('./src/components/TheTabbar.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanIcon: typeof import('vant/es')['Icon']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
  }
}
